// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "ClipHelm",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "ClipHelmCore", targets: ["ClipHelmCore"]),
        .library(name: "ClipHelmSecurity", targets: ["ClipHelmSecurity"]),
        .library(name: "ClipHelmOpenRouter", targets: ["ClipHelmOpenRouter"]),
        .library(name: "ClipHelmSources", targets: ["ClipHelmSources"]),
        .library(name: "ClipHelmMedia", targets: ["ClipHelmMedia"]),
        .library(name: "ClipHelmTranscription", targets: ["ClipHelmTranscription"]),
        .library(name: "ClipHelmAnalysis", targets: ["ClipHelmAnalysis"]),
        .library(name: "ClipHelmMoments", targets: ["ClipHelmMoments"]),
        .library(name: "ClipHelmEditing", targets: ["ClipHelmEditing"]),
        .library(name: "ClipHelmFraming", targets: ["ClipHelmFraming"]),
        .library(name: "ClipHelmFramingVision", targets: ["ClipHelmFramingVision"]),
        .library(name: "ClipHelmLayouts", targets: ["ClipHelmLayouts"]),
        .library(name: "ClipHelmLayoutVision", targets: ["ClipHelmLayoutVision"]),
        .library(name: "ClipHelmPacing", targets: ["ClipHelmPacing"]),
        .executable(name: "ClipHelmApp", targets: ["ClipHelmApp"]),
    ],
    targets: [
        .target(name: "ClipHelmCore"),
        .target(name: "ClipHelmSecurity"),
        .target(name: "ClipHelmOpenRouter", dependencies: ["ClipHelmSecurity"]),
        .target(name: "ClipHelmMedia", dependencies: ["ClipHelmCore"]),
        .target(name: "ClipHelmTranscription", dependencies: ["ClipHelmCore", "ClipHelmMedia", "ClipHelmOpenRouter"]),
        .target(name: "ClipHelmAnalysis", dependencies: ["ClipHelmCore", "ClipHelmMedia"]),
        .target(name: "ClipHelmMoments", dependencies: ["ClipHelmCore", "ClipHelmAnalysis", "ClipHelmOpenRouter"]),
        .target(name: "ClipHelmFraming", dependencies: ["ClipHelmCore", "ClipHelmAnalysis"]),
        .target(name: "ClipHelmFramingVision", dependencies: ["ClipHelmCore", "ClipHelmAnalysis", "ClipHelmFraming", "ClipHelmMedia", "ClipHelmOpenRouter"]),
        .target(name: "ClipHelmLayouts", dependencies: ["ClipHelmCore", "ClipHelmAnalysis", "ClipHelmMedia"]),
        .target(name: "ClipHelmLayoutVision", dependencies: ["ClipHelmCore", "ClipHelmAnalysis", "ClipHelmLayouts", "ClipHelmMedia", "ClipHelmOpenRouter"]),
        .target(name: "ClipHelmPacing", dependencies: ["ClipHelmCore", "ClipHelmAnalysis"]),
        .target(name: "ClipHelmEditing", dependencies: ["ClipHelmCore", "ClipHelmAnalysis", "ClipHelmFraming", "ClipHelmLayouts", "ClipHelmPacing"]),
        .target(name: "ClipHelmSources", dependencies: ["ClipHelmCore", "ClipHelmMedia"]),
        .executableTarget(name: "ClipHelmApp", dependencies: ["ClipHelmCore", "ClipHelmSecurity", "ClipHelmOpenRouter", "ClipHelmSources", "ClipHelmMedia", "ClipHelmTranscription", "ClipHelmAnalysis", "ClipHelmMoments"]),
        .testTarget(name: "ClipHelmCoreTests", dependencies: ["ClipHelmCore"]),
        .testTarget(name: "ClipHelmSecurityTests", dependencies: ["ClipHelmSecurity"]),
        .testTarget(name: "ClipHelmOpenRouterTests", dependencies: ["ClipHelmOpenRouter", "ClipHelmSecurity"]),
        .testTarget(name: "ClipHelmSourcesTests", dependencies: ["ClipHelmSources", "ClipHelmCore"],
                    resources: [.process("Fixtures")]),
        .testTarget(name: "ClipHelmMediaTests", dependencies: ["ClipHelmMedia", "ClipHelmCore"],
                    resources: [.process("Fixtures")]),
        .testTarget(name: "ClipHelmTranscriptionTests", dependencies: ["ClipHelmTranscription", "ClipHelmCore", "ClipHelmMedia", "ClipHelmOpenRouter"],
                    resources: [.process("Fixtures")]),
        .testTarget(name: "ClipHelmAnalysisTests", dependencies: ["ClipHelmAnalysis", "ClipHelmCore", "ClipHelmMedia"],
                    resources: [.process("Fixtures")]),
        .testTarget(name: "ClipHelmMomentsTests", dependencies: ["ClipHelmMoments", "ClipHelmCore", "ClipHelmAnalysis", "ClipHelmOpenRouter"]),
        .testTarget(name: "ClipHelmEditingTests", dependencies: ["ClipHelmEditing", "ClipHelmCore", "ClipHelmAnalysis"]),
        .testTarget(name: "ClipHelmFramingTests", dependencies: ["ClipHelmFraming", "ClipHelmFramingVision", "ClipHelmCore", "ClipHelmAnalysis", "ClipHelmMedia", "ClipHelmOpenRouter"]),
        .testTarget(name: "ClipHelmLayoutsTests", dependencies: ["ClipHelmLayouts", "ClipHelmLayoutVision", "ClipHelmCore", "ClipHelmAnalysis", "ClipHelmMedia", "ClipHelmOpenRouter"]),
        .testTarget(name: "ClipHelmPacingTests", dependencies: ["ClipHelmPacing", "ClipHelmEditing", "ClipHelmCore", "ClipHelmAnalysis"]),
        .testTarget(name: "ClipHelmAppTests", dependencies: ["ClipHelmApp", "ClipHelmCore"]),
    ]
)
